language: minimal
services:
  - docker
env:
  global:
    - ERRBIT_PATH=/tmp/errbit
before_script:
  - git clone https://github.com/errbit/errbit.git $ERRBIT_PATH
  - docker build --tag errbit-docs-builder .
  - docker run --user $UID --volume "$PWD:/srv" errbit-docs-builder bundle install
script:
  - docker run -e ERRBIT_PATH="$ERRBIT_PATH" --user $UID --volume "$PWD:/srv" --volume "$ERRBIT_PATH:$ERRBIT_PATH" errbit-docs-builder bundle exec jekyll build
  - docker run -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" --user $UID --volume "$PWD:/srv" errbit-docs-builder bundle exec s3_website push
cache:
  directories:
   - vendor/bundle
