---
encoding: utf-8
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - s3_website.yml
  - CNAME
  - lib
kramdown:
  input: GFM
  gfm_quirks: paragraph_end
  parse_block_html: true
defaults:
  -
    values:
      layout: "default"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - tmp
  - lib
  - bin
